export default [
  // 1. Crime Scene Table
  `CREATE TABLE crime_scene (
      id INTEGER PRIMARY KEY,
      date INTEGER,
      location TEXT,
      description TEXT
    );`,
  `INSERT INTO crime_scene (id, date, location, description) VALUES
      (1, 19860814, 'Lincoln Road Mall', 'Famous street art mural worth $200,000 deliberately destroyed. Surveillance footage shows organized vandalism.'),
      (2, 19860814, 'South Beach Club', 'A violent fight broke out between multiple patrons, resulting in severe injuries and extensive property damage. Security footage shows the incident started at the bar area.'),
      (3, 19860813, 'Downtown Alley', 'Armed robbery occurred with three masked perpetrators. Victims reported the suspects were carrying handguns and escaped with over $5,000 in cash and valuables.'),
      (4, 19860815, 'Palm Beach Resort', 'Guest reported missing jewelry worth $25,000 from their room safe. No signs of forced entry were found, suggesting possible inside job.'),
      (5, 19860816, 'Miami Convention Center', 'Corporate espionage case involving stolen classified documents from major tech company. Security cameras were disabled during the theft.'),
      (6, 19860817, 'Little Havana Restaurant', 'Sophisticated money laundering operation discovered after months of investigation. Multiple high-profile suspects identified and large sums of cash seized.'),
      (7, 19860818, 'Coconut Grove Park', 'Drug deal interrupted by rival gang, resulting in violent confrontation. Multiple shell casings found at scene but no casualties reported.'),
      (8, 19860819, 'Brickell Financial District', 'Elaborate bank robbery attempt involving tunnel system. Police responded before vault was breached, suspects fled leaving equipment behind.'),
      (9, 19860820, 'Art Deco Hotel', 'Priceless Picasso painting stolen from lobby during busy check-in time. Security footage shows professional thieves using sophisticated methods.'),
      (10, 19860821, 'Fisher Island Club', 'Prominent member reported systematic blackmail attempt involving compromising photos. Ransom demands exceed $100,000.'),
      (11, 19860822, 'Vizcaya Museum', 'Rare 15th century artifact disappeared during special exhibition. Alarm systems were professionally bypassed, suggesting inside knowledge.'),
      (12, 19860823, 'Bayside Marketplace', 'Large-scale counterfeit operation discovered producing fake designer goods. Multiple arrests made and equipment seized.'),
      (13, 19860824, 'Miami Beach Marina', 'International smuggling operation intercepted with contraband worth millions. Multiple boats and suspects detained.'),
      (14, 19860825, 'Coral Gables Theater', 'Detailed bomb threat caused evacuation of 500 people. Extensive search revealed elaborate hoax device.'),
      (15, 19860826, 'Venetian Pool', 'Significant vandalism reported with damages exceeding $50,000. Historic structures defaced and equipment destroyed.'),
      (16, 19860827, 'Miracle Mile', 'Coordinated series of high-end store break-ins resulted in over $200,000 in stolen merchandise. Professional crew suspected.'),
      (17, 19860828, 'Calle Ocho', 'Major street fight involving rival gangs resulted in multiple serious injuries and one critical condition. Numerous weapons recovered.'),
      (18, 19860829, 'Port of Miami', 'Sophisticated cargo container theft involving forged documents and insider assistance. High-value electronics stolen.'),
      (19, 19860830, 'Miami River', 'Decomposed body discovered in abandoned luxury yacht. Evidence suggests victim was tortured before death.'),
      (20, 19860831, 'South Pointe Park', 'Major drug bust operation resulted in seizure of cocaine worth $2 million and multiple high-level arrests.'),
      (21, 19860901, 'Ocean Drive Hotel', 'Celebrity jewels worth $500,000 stolen from supposedly secure safe. Professional thieves bypassed advanced security system.'),
      (22, 19860902, 'Lincoln Road Mall', 'Armed robbery at high-end jewelry store resulted in $1 million loss. Three armed suspects overwhelmed security.'),
      (23, 19860903, 'Española Way', 'Suspicious restaurant fire investigated as arson. Evidence of accelerants found and previous threats reported.'),
      (24, 19860904, 'Wynwood Arts District', 'Famous street art mural worth $200,000 deliberately destroyed. Surveillance footage shows organized vandalism.'),
      (25, 19860905, 'Design District', 'Coordinated robbery of luxury fashion store during delivery. Armed suspects stole entire shipment of designer goods.'),
      (26, 19860906, 'Miami International Airport', 'Complex drug smuggling ring uncovered involving multiple airline employees and sophisticated concealment methods.'),
      (27, 19860907, 'Marlins Stadium', 'Large-scale ticket fraud scheme exposed involving counterfeit tickets and corrupt employees.'),
      (28, 19860908, 'Overtown', 'Gang-related shooting resulted in multiple injuries and extensive property damage. Multiple weapons recovered.'),
      (29, 19860909, 'Miami Gardens', 'Violent home invasion targeting elderly couple. Suspects tortured victims before stealing valuables.'),
      (30, 19860910, 'Coral Way', 'Professional car theft ring dismantled after months of surveillance. Multiple luxury vehicles recovered.'),
      (31, 19860911, 'Key Biscayne Beach', 'Major environmental crime discovered involving illegal toxic waste dumping. Extensive damage to marine life reported.'),
      (32, 19860912, 'Flagler Street', 'Armed bank robbery in progress with hostage situation. Multiple suspects cornered inside building.'),
      (33, 19860913, 'Government Center', 'Complex corruption case involving multiple city officials and construction contracts worth millions.'),
      (34, 19860914, 'Miami Seaquarium', 'Sophisticated attempt to steal rare marine specimens thwarted. International trafficking ring suspected.'),
      (35, 19860915, 'Jungle Island', 'Theft of endangered species worth $100,000 reported. Professional animal traffickers suspected.'),
      (36, 19860916, 'Fairchild Gardens', 'Rare orchid specimens worth $75,000 stolen during night. Security systems professionally disabled.'),
      (37, 19860917, 'Matheson Hammock Park', 'Badly decomposed body discovered in mangroves showing signs of execution-style murder.'),
      (38, 19860918, 'Crandon Park', 'Systematic environmental vandalism causing extensive damage to protected habitat. Multiple sites targeted.'),
      (39, 19860919, 'Virginia Key', 'Major illegal dumping operation discovered with toxic waste threatening water supply.'),
      (40, 19860920, 'Rickenbacker Causeway', 'High-speed chase ended in multiple vehicle collision and arrest of drug trafficking suspects.'),
      (41, 19860921, 'Venetian Islands', 'Sophisticated home burglary targeting art collection worth millions. Security systems bypassed.'),
      (42, 19860922, 'Star Island', 'Celebrity stalking case involving death threats and attempted break-in at mansion.'),
      (43, 19860814, 'Coral Bay Marina', 'The body of an unidentified man was found near the docks. Two people were seen nearby: one who lives on 300ish "Ocean Drive" and another whose first name ends with "ul" and his last name ends with "ez".'),
      (44, 19860924, 'Hibiscus Island', 'Major art forgery ring discovered producing fake masterpieces worth millions.'),
      (45, 19860925, 'Miami Shores', 'Notorious serial burglar caught after year-long investigation. Multiple stolen items recovered.'),
      (46, 19860926, 'North Bay Village', 'Complex insurance fraud case involving staged accidents and corrupt medical professionals.'),
      (47, 19860927, 'Surfside', 'Violent beach assault involving multiple attackers. Victim in critical condition.'),
      (48, 19860928, 'Bal Harbour', 'Organized retail theft ring targeting luxury stores. Professional shoplifting crew identified.'),
      (49, 19860929, 'Sunny Isles Beach', 'Multi-million dollar real estate fraud scheme exposed involving fake property sales.'),
      (50, 19860930, 'Golden Beach', 'Armed home invasion at celebrity residence. Extensive property damage and theft reported.'),
      (51, 19861001, 'North Miami Beach', 'Dangerous car chase ended with multiple injuries and significant property damage.'),
      (52, 19861002, 'Aventura', 'Shopping mall shooting incident resulted in multiple injuries and mass panic.'),
      (53, 19861003, 'Oleta River Park', 'Major environmental crime involving illegal chemical dumping into protected waterway.'),
      (54, 19861004, 'Haulover Beach', 'Large-scale drug smuggling operation intercepted. Multiple boats and suspects detained.'),
      (55, 19861005, 'Collins Avenue', 'Brutal hotel room murder with signs of torture. Room completely ransacked.'),
      (56, 19861006, 'Washington Avenue', 'Nightclub shooting resulted in multiple casualties and extensive property damage.'),
      (57, 19861007, 'Alton Road', 'Armed robbery at convenience store with shots fired. One employee critically injured.'),
      (58, 19861008, 'West Avenue', 'Violent apartment break-in with elderly resident assaulted. Valuable antiques stolen.'),
      (59, 19861009, 'Belle Isle', 'Domestic disturbance escalated to hostage situation. SWAT team deployed.'),
      (60, 19861010, 'Sunset Harbour', 'Luxury boat theft involving professional criminals. Multiple vessels targeted.'),
      (61, 19861011, 'North Beach', 'Series of violent tourist muggings reported. Multiple victims hospitalized.'),
      (62, 19861012, 'Mid Beach', 'Professional hotel safe robbery involving sophisticated tools and insider information.'),
      (63, 19861013, 'South Beach', 'Restaurant shooting during busy dinner service. Multiple witnesses interviewed.'),
      (64, 19861014, 'Lummus Park', 'Major drug deal interrupted by rival gang. Multiple weapons recovered.'),
      (65, 19861015, 'Flamingo Park', 'Large-scale theft of expensive athletic equipment from sports facility.'),
      (66, 19861016, 'South Pointe', 'Violent assault on pier resulting in victim being thrown into ocean.'),
      (67, 19861017, 'Government Cut', 'Major smuggling operation busted with contraband worth millions seized.'),
      (68, 19861018, 'Fisher Island', 'Professional jewelry heist targeting multiple high-end residences.'),
      (69, 19861019, 'Dodge Island', 'Complex cargo theft investigation involving corrupt port employees.'),
      (70, 19861020, 'Watson Island', 'Attempted theft of private aircraft thwarted by security personnel.'),
      (71, 19861021, 'MacArthur Causeway', 'High-speed pursuit resulted in multiple vehicle accidents and injuries.'),
      (72, 19861022, 'Venetian Causeway', 'Fatal hit and run incident involving luxury vehicle. Driver fled scene.'),
      (73, 19861023, 'Julia Tuttle Causeway', 'Body discovered with multiple gunshot wounds. Gang-related suspected.'),
      (74, 19861024, 'Downtown Miami', 'Sophisticated office building break-in targeting corporate secrets.'),
      (75, 19861025, 'Media and Entertainment District', 'Major vandalism at television studio causing broadcast interruption.'),
      (76, 19861026, 'Edgewater', 'Waterfront assault case involving multiple attackers and stolen boat.'),
      (77, 19861027, 'Midtown', 'Professional art gallery theft targeting specific high-value pieces.'),
      (78, 19861028, 'Design District', 'Armed robbery at fashion warehouse during inventory delivery.'),
      (79, 19861029, 'Little Haiti', 'Violent corner store robbery resulting in owner hospitalization.'),
      (80, 19861030, 'Upper Eastside', 'Home invasion case involving torture and significant property theft.'),
      (81, 19861031, 'Little River', 'Major industrial theft of expensive manufacturing equipment reported.'),
      (82, 19861101, 'West Little River', 'Violent gang activity resulting in multiple injuries and property damage.'),
      (83, 19861102, 'Liberty City', 'Armed robbery at convenience store with multiple shots fired.'),
      (84, 19861103, 'Model City', 'Professional car theft ring discovered operating sophisticated chop shop.'),
      (85, 19861104, 'Brownsville', 'Major drug house raid resulted in multiple arrests and evidence seizure.'),
      (86, 19861105, 'Allapattah', 'Professional warehouse break-in targeting high-value electronics.'),
      (87, 19861106, 'Grapeland Heights', 'Extensive park vandalism causing significant damage to facilities.'),
      (88, 19861107, 'Civic Center', 'Complex political corruption case involving bribes and kickbacks.'),
      (89, 19861108, 'Spring Garden', 'Historic home burglary targeting valuable antique collection.'),
      (90, 19861109, 'Riverside', 'Major river pollution incident causing extensive environmental damage.'),
      (91, 19861110, 'Little Havana', 'Suspicious restaurant fire investigated as insurance fraud scheme.'),
      (92, 19861111, 'The Roads', 'Illegal street racing incident resulted in multiple vehicle accidents.'),
      (93, 19861112, 'Shenandoah', 'Series of coordinated home burglaries targeting elderly residents.'),
      (94, 19861113, 'Silver Bluff', 'Armed jewelry store robbery with multiple suspects and hostages.'),
      (95, 19861114, 'Coral Way', 'Sophisticated bank robbery attempt involving tunnel system.'),
      (96, 19861115, 'Brickell', 'Major corporate espionage case involving stolen trade secrets.'),
      (97, 19861116, 'Coconut Grove', 'Large-scale marina theft targeting expensive boat equipment.'),
      (98, 19861117, 'Coral Gables', 'Professional art museum heist involving multiple valuable pieces.'),
      (99, 19861118, 'South Miami', 'Shopping mall shooting incident with multiple casualties reported.'),
      (100, 19861119, 'Kendall', 'Extensive suburban break-in spree targeting multiple residences.')
    ;`,

  // 2. Person Table (Contains all people: suspects, witnesses, and other characters)
  `CREATE TABLE person (
      id INTEGER PRIMARY KEY,
      name TEXT,
      alias TEXT,
      occupation TEXT,
      address TEXT
    );`,
  `INSERT INTO person (id, name, alias, occupation, address) VALUES
      (1, 'Marco Romano', 'The Shadow', 'Fisherman', '22 Ocean Drive'),
      (2, 'Antonio Costa', 'The Shark', 'Nightclub Owner', '45 Sunset Ave'),
      (3, 'Vincent Rossi', 'Lucky V', 'Smuggler', '88 Harbor St'),
      (4, 'Frank Marino', 'The Ghost', 'Contractor', '101 Palm Blvd'),
      (5, 'Michael Santos', 'Silent Mike', 'Bartender', '33 Ocean Drive'),
      (6, 'James Wilson', 'The Wolf', 'Security Guard', '156 Marina Way'),
      (7, 'Robert Smith', 'Red Rob', 'Mechanic', '789 Beach Road'),
      (8, 'Thomas Brown', 'The Fox', 'Dock Worker', '234 Port Street'),
      (9, 'David Clark', 'Dark Dave', 'Warehouse Manager', '567 Bay Drive'),
      (10, 'John Anderson', 'Quick Jack', 'Boat Captain', '890 Pier Lane'),
      (11, 'Paul Thompson', 'The Eagle', 'Private Investigator', '123 Coast Ave'),
      (12, 'George Davis', 'Silent Storm', 'Hotel Manager', '456 Wave Street'),
      (13, 'Kevin White', 'The Phantom', 'Casino Dealer', '789 Shell Road'),
      (14, 'Richard Moore', 'The Raven', 'Restaurant Owner', '321 Coral Way'),
      (15, 'Joseph Taylor', 'Jazz Joe', 'Musician', '654 Sand Drive'),
      (16, 'Daniel Martin', 'The Dragon', 'Boxing Trainer', '987 Palm Street'),
      (17, 'Christopher Lee', 'The Cobra', 'Private Driver', '234 Beach Blvd'),
      (18, 'Steven King', 'The Knight', 'Real Estate Agent', '567 Ocean View'),
      (19, 'Edward Baker', 'Easy Ed', 'Car Salesman', '890 Marina Drive'),
      (20, 'Brian Hall', 'The Bear', 'Bouncer', '123 Harbor Lane'),
      (21, 'Ronald Scott', 'The Rock', 'Construction Worker', '456 Dock Road'),
      (22, 'Anthony Hill', 'The Anchor', 'Sailor', '789 Coast Street'),
      (23, 'Kenneth Green', 'The Key', 'Locksmith', '321 Wave Drive'),
      (24, 'Jason Adams', 'The Jaguar', 'Race Car Driver', '654 Shell Lane'),
      (25, 'Jeffrey Nelson', 'The Judge', 'Attorney', '987 Coral Street'),
      (26, 'Ryan Phillips', 'Red Ryan', 'Firefighter', '234 Sand Road'),
      (27, 'Jacob Campbell', 'The Joker', 'Comedian', '567 Palm Drive'),
      (28, 'Gary Mitchell', 'The Giant', 'Bodyguard', '890 Beach Way'),
      (29, 'Nicholas Roberts', 'Night Nick', 'Club DJ', '123 Ocean Road'),
      (30, 'Eric Carter', 'The Eagle', 'Pilot', '456 Marina Street'),
      (31, 'Stephen Cooper', 'The Spider', 'Web Developer', '789 Harbor Drive'),
      (32, 'Andrew Richardson', 'The Artist', 'Painter', '321 Dock Lane'),
      (33, 'Donald Cook', 'The Duke', 'Business Owner', '654 Coast Road'),
      (34, 'Mark Morgan', 'The Mask', 'Theater Actor', '987 Wave Street'),
      (35, 'Charles Peterson', 'The Chief', 'Police Officer', '234 Shell Drive'),
      (36, 'Sean Turner', 'The Snake', 'Martial Arts Instructor', '567 Coral Lane'),
      (37, 'Philip Collins', 'The Phoenix', 'Insurance Agent', '890 Sand Street'),
      (38, 'Raymond Wood', 'The Razor', 'Barber', '123 Palm Road'),
      (39, 'Gregory Stewart', 'The Ghost', 'Paranormal Investigator', '456 Beach Drive'),
      (40, 'Joshua Reed', 'The Jet', 'Travel Agent', '789 Ocean Lane'),
      (41, 'Dennis Bailey', 'The Diamond', 'Jeweler', '321 Marina Road'),
      (42, 'Peter Bell', 'The Panther', 'Wildlife Photographer', '654 Harbor Street'),
      (43, 'Douglas Murphy', 'The Dragon', 'Chef', '987 Dock Drive'),
      (44, 'Henry Rivera', 'The Hunter', 'Private Detective', '234 Coast Lane'),
      (45, 'Carl Cooper', 'The Crow', 'Artist', '567 Wave Road'),
      (46, 'Arthur Bryant', 'The Arrow', 'Archery Instructor', '890 Shell Street'),
      (47, 'Lawrence Powell', 'The Lion', 'Zoo Keeper', '123 Coral Drive'),
      (48, 'Terry Butler', 'The Tiger', 'Martial Artist', '456 Sand Lane'),
      (49, 'Sean Fisher', 'The Shark', 'Marine Biologist', '789 Palm Street'),
      (50, 'Bruce Barnes', 'The Bull', 'Stock Broker', '321 Beach Road'),
      (51, 'Wayne Ross', 'The Wizard', 'Magician', '654 Ocean Street'),
      (52, 'Eugene Henderson', 'The Eagle', 'Bird Trainer', '987 Marina Lane'),
      (53, 'Ralph Coleman', 'The Rook', 'Chess Instructor', '234 Harbor Road'),
      (54, 'Roy Jenkins', 'The Ranger', 'Park Ranger', '567 Dock Street'),
      (55, 'Randy Perry', 'The Rebel', 'Motorcycle Mechanic', '890 Coast Drive'),
      (56, 'Louis Patterson', 'The Leopard', 'Track Coach', '123 Wave Street'),
      (57, 'Bobby Hughes', 'The Baron', 'Hotel Owner', '456 Shell Road'),
      (58, 'Scott Foster', 'The Scout', 'Talent Agent', '789 Coral Lane'),
      (59, 'Victor Gray', 'The Viper', 'Snake Handler', '321 Sand Street'),
      (60, 'Walter Long', 'The Whale', 'Marine Tour Guide', '654 Palm Drive'),
      (61, 'Harold Ward', 'The Hawk', 'Bird Watcher', '987 Beach Street'),
      (62, 'Jesse Brooks', 'The Judge', 'Court Clerk', '234 Ocean Drive'),
      (63, 'Carlos Simmons', 'The Cardinal', 'Church Worker', '567 Marina Road'),
      (64, 'Arthur Hayes', 'The Ace', 'Card Dealer', '890 Harbor Lane'),
      (65, 'Lawrence Gordon', 'The Lion', 'Circus Performer', '123 Dock Street'),
      (66, 'Keith Hamilton', 'The Knight', 'Chess Master', '456 Coast Drive'),
      (67, 'Jerry Graham', 'The Jackal', 'Private Guard', '789 Wave Lane'),
      (68, 'Terry Sullivan', 'The Torch', 'Fire Performer', '321 Shell Street'),
      (69, 'Ray Wallace', 'The Raven', 'Night Watchman', '654 Coral Road'),
      (70, 'Joe Woods', 'The Jester', 'Street Performer', '987 Sand Drive'),
      (71, 'Albert Cole', 'The Albatross', 'Ship Captain', '234 Palm Lane'),
      (72, 'Willie West', 'The Warrior', 'Boxing Coach', '567 Beach Street'),
      (73, 'Alan Reynolds', 'The Alchemist', 'Chemist', '890 Ocean Road'),
      (74, 'Ralph Fox', 'The Ruler', 'School Principal', '123 Marina Street'),
      (75, 'Eugene Jordan', 'The Emperor', 'Business Consultant', '456 Harbor Drive'),
      (76, 'Bobby Grant', 'The Baron', 'Wine Merchant', '789 Dock Road'),
      (77, 'Howard Lynch', 'The Hunter', 'Game Warden', '321 Coast Lane'),
      (78, 'Fred Harrison', 'The Falcon', 'Air Traffic Controller', '654 Wave Drive'),
      (79, 'Wayne Ellis', 'The Wizard', 'Software Developer', '987 Shell Lane'),
      (80, 'Steve Stevens', 'The Storm', 'Weather Reporter', '234 Coral Street'),
      (81, 'Earl Stone', 'The Echo', 'Sound Engineer', '567 Sand Drive'),
      (82, 'Craig Johnston', 'The Crown', 'Jewelry Designer', '890 Palm Road'),
      (83, 'Stanley Black', 'The Star', 'Astronomer', '123 Beach Lane'),
      (84, 'Tommy Dean', 'The Thunder', 'Storm Chaser', '456 Ocean Street'),
      (85, 'Leon Carr', 'The Legend', 'History Professor', '789 Marina Drive'),
      (86, 'Gordon Mills', 'The Guardian', 'Museum Security', '321 Harbor Road'),
      (87, 'Norman Holmes', 'The Navigator', 'Ship Navigator', '654 Dock Street'),
      (88, 'Vernon Rice', 'The Vulture', 'Debt Collector', '987 Coast Drive'),
      (89, 'Harvey Burns', 'The Hurricane', 'Weather Forecaster', '234 Wave Road'),
      (90, 'Lewis Shaw', 'The Lightning', 'Electrician', '567 Shell Street'),
      (91, 'Milton Ford', 'The Mystic', 'Fortune Teller', '890 Coral Lane'),
      (92, 'Claude Fleming', 'The Clock', 'Watch Maker', '123 Sand Drive'),
      (93, 'Lester Owens', 'The Legend', 'Tour Guide', '456 Palm Street'),
      (94, 'Cecil Daniels', 'The Cipher', 'Code Breaker', '789 Beach Drive'),
      (95, 'Herman Cunningham', 'The Hammer', 'Construction Foreman', '321 Ocean Lane'),
      (96, 'Floyd Duncan', 'The Flash', 'Photography', '654 Marina Street'),
      (97, 'Wallace Armstrong', 'The Wave', 'Surf Instructor', '987 Harbor Drive'),
      (98, 'Lloyd Weber', 'The Lotus', 'Yoga Teacher', '234 Dock Road'),
      (99, 'Max Bishop', 'The Master', 'Chess Champion', '567 Coast Street'),
      (100, 'Sam Knight', 'The Shadow', 'Private Eye', '890 Wave Drive'),
      (101, 'Carlos Mendez', 'Los Ojos', 'Fisherman', '369 Ocean Drive'),
      (102, 'Raul Gutierrez', 'The Cobra', 'Nightclub Owner', '45 Sunset Ave'),
      (103, 'Luis Sanchez', 'Lucky Lou', 'Smuggler', '88 Harbor St'),
      (104, 'Diego Ramirez', 'El Fuego', 'Contractor', '101 Palm Blvd'),
      (105, 'Victor Martinez', 'Slick Vic', 'Bartender', '33 Ocean Drive'),
      (106, 'Marcus Thompson', 'The Whisper', 'Locksmith', '55 Marina Lane'),
      (107, 'Derek Anderson', 'The Drifter', 'Sailor', '89 Coral Way'),
      (108, 'Philip Norton', 'The Phoenix', 'Fire Inspector', '12 Shell Beach'),
      (109, 'Gregory Walsh', 'The Ghost', 'Night Guard', '44 Palm Court'),
      (110, 'Kenneth Blake', 'The King', 'Chess Player', '77 Harbor View'),
      (111, 'Russell Wright', 'The Rook', 'Security Guard', '91 Wave Street'),
      (112, 'Douglas Pierce', 'The Duke', 'Art Dealer', '23 Sunset Lane'),
      (113, 'Roger Matthews', 'The Rock', 'Gym Owner', '67 Marina Circle'),
      (114, 'Vincent Parker', 'The Voice', 'Radio Host', '88 Coral Cove'),
      (115, 'Leonard Ross', 'The Lion', 'Animal Trainer', '34 Shell Road'),
      (116, 'Walter Morgan', 'The Wolf', 'Forest Ranger', '59 Palm Avenue'),
      (117, 'Harold Cooper', 'The Hawk', 'Pilot', '82 Harbor Road'),
      (118, 'Samuel Wilson', 'The Snake', 'Reptile Expert', '15 Wave Court'),
      (119, 'Bernard Taylor', 'The Bear', 'Wrestling Coach', '93 Marina Way'),
      (120, 'Frederick Brown', 'The Fox', 'Private Detective', '28 Coral Street'),
      (121, 'Albert Richardson', 'The Ace', 'Poker Player', '71 Shell Lane'),
      (122, 'Eugene Morris', 'The Eagle', 'Bird Trainer', '44 Palm Street'),
      (123, 'Raymond Clark', 'The Raven', 'Book Store Owner', '66 Harbor Lane'),
      (124, 'Thomas White', 'The Tiger', 'Martial Arts Instructor', '89 Wave Road'),
      (125, 'Gerald Scott', 'The Giant', 'Bouncer', '32 Marina Drive'),
      (126, 'Peter Mitchell', 'The Phantom', 'Magician', '75 Coral Road'),
      (127, 'Donald Turner', 'The Dragon', 'Restaurant Owner', '18 Shell Way'),
      (128, 'Bruce Phillips', 'The Bull', 'Stock Broker', '91 Palm Place'),
      (129, 'Anthony Campbell', 'The Arrow', 'Archery Instructor', '24 Harbor Walk'),
      (130, 'Charles Edwards', 'The Crown', 'Jeweler', '67 Wave Avenue'),
      (131, 'Frank Collins', 'The Flame', 'Glass Blower', '83 Marina Place'),
      (132, 'Robert Stewart', 'The Rain', 'Meteorologist', '36 Coral Path'),
      (133, 'James Peterson', 'The Judge', 'Retired Lawyer', '59 Shell Circle'),
      (134, 'Michael Bennett', 'The Moon', 'Astronomer', '92 Palm Walk'),
      (135, 'William Rogers', 'The Wind', 'Sailing Instructor', '15 Harbor Point'),
      (136, 'Richard Wood', 'The River', 'Boat Captain', '48 Wave Place'),
      (137, 'Joseph Carter', 'The Joker', 'Comedian', '71 Marina Boulevard'),
      (138, 'David Hughes', 'The Diamond', 'Gem Dealer', '94 Coral Avenue'),
      (139, 'Paul Price', 'The Prophet', 'Fortune Teller', '27 Shell Drive'),
      (140, 'Mark Russell', 'The Mirror', 'Glass Artist', '63 Palm Bay'),
      (141, 'Steven Cook', 'The Storm', 'Coast Guard', '86 Harbor Circle'),
      (142, 'Kevin Morgan', 'The Knight', 'Security Chief', '19 Wave Bay'),
      (143, 'Edward Baker', 'The Echo', 'Music Producer', '52 Marina Court'),
      (144, 'Brian Young', 'The Baron', 'Wine Collector', '75 Coral Lane'),
      (145, 'George King', 'The Bishop', 'Chess Teacher', '38 Shell Point'),
      (146, 'Ronald Lee', 'The Runner', 'Track Coach', '81 Palm Road'),
      (147, 'Larry Hall', 'The Light', 'Lighthouse Keeper', '14 Harbor Way'),
      (148, 'Jeffrey Allen', 'The Jack', 'Card Dealer', '47 Wave Walk'),
      (149, 'Dennis Hill', 'The Dawn', 'Baker', '93 Marina Path'),
      (150, 'Gary Adams', 'The Dust', 'Desert Guide', '26 Coral Point'),
      (151, 'Stephen Ward', 'The Star', 'Theater Director', '69 Shell Street'),
      (152, 'Henry Brooks', 'The Heart', 'Cardiologist', '82 Palm Lane'),
      (153, 'Carl Butler', 'The Clock', 'Watchmaker', '15 Harbor Avenue'),
      (154, 'Ralph Fisher', 'The Fog', 'Lighthouse Worker', '58 Wave Point'),
      (155, 'Roger Nelson', 'The Rose', 'Florist', '71 Marina Street'),
      (156, 'Eugene Powell', 'The Eye', 'Optometrist', '94 Coral Drive'),
      (157, 'Arthur Long', 'The Axe', 'Lumberjack', '27 Shell Bay'),
      (158, 'Lawrence Ross', 'The Lens', 'Photographer', '63 Palm Point'),
      (159, 'Keith Watson', 'The Key', 'Locksmith', '86 Harbor Drive'),
      (160, 'Jerry Bryant', 'The Jade', 'Gem Collector', '19 Wave Court'),
      (161, 'Terry Cooper', 'The Tide', 'Marine Biologist', '52 Marina Bay'),
      (162, 'Ray Marshall', 'The Ring', 'Boxing Coach', '75 Coral Walk'),
      (163, 'Joe Foster', 'The Jump', 'Skydiving Instructor', '38 Shell Avenue'),
      (164, 'Albert Gray', 'The Anchor', 'News Anchor', '81 Palm Way'),
      (165, 'Willie Shaw', 'The Web', 'IT Specialist', '14 Harbor Court'),
      (166, 'Alan Hunt', 'The Wing', 'Flight Instructor', '47 Wave Circle'),
      (167, 'Ralph Crawford', 'The Claw', 'Crane Operator', '93 Marina Avenue'),
      (168, 'Eugene Simpson', 'The Spark', 'Electrician', '26 Coral Bay'),
      (169, 'Bobby Porter', 'The Blade', 'Knife Thrower', '69 Shell Walk'),
      (170, 'Howard Griffin', 'The Hook', 'Fishing Guide', '82 Palm Drive'),
      (171, 'Fred Warren', 'The Flame', 'Welder', '15 Harbor Street'),
      (172, 'Wayne Mason', 'The Wave', 'Surfing Instructor', '58 Wave Bay'),
      (173, 'Steve Fuller', 'The Shield', 'Police Officer', '71 Marina Point'),
      (174, 'Earl Palmer', 'The Edge', 'Rock Climber', '94 Coral Court'),
      (175, 'Craig Spencer', 'The Chain', 'Bike Mechanic', '27 Shell Court'),
      (176, 'Stanley Gordon', 'The Shell', 'Marine Biologist', '63 Palm Circle'),
      (177, 'Tommy Black', 'The Shadow', 'Stage Hand', '86 Harbor Point'),
      (178, 'Leon Davidson', 'The Leaf', 'Botanist', '19 Wave Drive'),
      (179, 'Gordon Fleming', 'The Glacier', 'Ice Sculptor', '52 Marina Walk'),
      (180, 'Norman Hawkins', 'The Hammer', 'Construction Worker', '75 Coral Place'),
      (181, 'Vernon Dixon', 'The Vault', 'Bank Manager', '38 Shell Road'),
      (182, 'Harvey Morrison', 'The Harbor', 'Port Authority', '81 Palm Court'),
      (183, 'Lewis Pearson', 'The Lens', 'Camera Repair', '14 Harbor Bay'),
      (184, 'Milton Douglas', 'The Mist', 'Special Effects', '47 Wave Lane'),
      (185, 'Claude Newman', 'The Crystal', 'Geologist', '93 Marina Road'),
      (186, 'Lester Larson', 'The Link', 'Chain Maker', '26 Coral Way'),
      (187, 'Cecil Henderson', 'The Cave', 'Cave Guide', '69 Shell Lane'),
      (188, 'Herman Robertson', 'The Horn', 'Music Teacher', '82 Palm Avenue'),
      (189, 'Floyd Ferguson', 'The Flash', 'News Reporter', '15 Harbor Lane'),
      (190, 'Wallace Stone', 'The Wall', 'Mason', '58 Wave Place'),
      (191, 'Lloyd Hamilton', 'The Loop', 'Roller Coaster Operator', '71 Marina Lane'),
      (192, 'Max Patterson', 'The Mountain', 'Mountain Guide', '94 Coral Street'),
      (193, 'Sam Johnston', 'The Stream', 'River Guide', '27 Shell Place'),
      (194, 'Dale Armstrong', 'The Dust', 'House Cleaner', '63 Palm Path'),
      (195, 'Don Wallace', 'The Door', 'Carpenter', '86 Harbor Walk'),
      (196, 'Pete Bishop', 'The Path', 'Trail Guide', '19 Wave Path'),
      (197, 'Nick Reynolds', 'The Night', 'Astronomer', '52 Marina Place'),
      (198, 'Andy Richardson', 'The Arc', 'Bridge Engineer', '75 Coral Boulevard'),
      (199, 'Tim Harrison', 'The Torch', 'Welder', '38 Shell Circle'),
      (200, 'Chris Davidson', 'The Cloud', 'Pilot', '81 Palm Boulevard'),
      (201, 'Matthew Black', 'The Mask', 'Theater Actor', '14 Harbor Circle'),
      (202, 'Daniel Wright', 'The Drift', 'River Guide', '47 Wave Boulevard'),
      (203, 'Patrick Stone', 'The Peak', 'Mountain Climber', '93 Marina Circle'),
      (204, 'Alexander Foster', 'The Atlas', 'Map Maker', '26 Coral Boulevard'),
      (205, 'Benjamin Cooper', 'The Beacon', 'Lighthouse Keeper', '69 Shell Boulevard')
    ;`,

  // 3. Interviews Table
  `CREATE TABLE interviews (
      id INTEGER PRIMARY KEY,
      person_id INTEGER,
      transcript TEXT,
      FOREIGN KEY (person_id) REFERENCES person(id)
    );`,
  `INSERT INTO interviews (id, person_id, transcript) VALUES
      (1, 127, 'I saw a suspicious man in a black coat running from the marina that night.'),
      (2, 45, NULL),
      (3, 189, 'The victim was arguing with someone at the bar earlier that evening.'),
      (4, 23, NULL),
      (5, 156, 'I heard gunshots around midnight near the docks.'),
      (6, 78, NULL),
      (7, 134, 'A speedboat left the marina at high speed shortly after the incident.'),
      (8, 12, NULL),
      (9, 167, 'The victim seemed nervous and kept looking over his shoulder all day.'),
      (10, 89, NULL),
      (11, 145, 'I noticed someone tampering with one of the boats earlier that afternoon.'),
      (12, 34, NULL),
      (13, 178, 'There was a heated discussion about money near warehouse B.'),
      (14, 56, NULL),
      (15, 123, 'I saw someone throwing something into the water around 2 AM.'),
      (16, 67, NULL),
      (17, 190, 'The security cameras were mysteriously disabled that night.'),
      (18, 43, NULL),
      (19, 112, 'A silver briefcase exchanged hands behind the fuel station.'),
      (20, 88, NULL),
      (21, 156, 'Someone in a fishing boat was acting strangely near the crime scene.'),
      (22, 32, NULL),
      (23, 167, 'I heard a loud argument in a foreign language before everything went quiet.'),
      (24, 91, NULL),
      (25, 145, 'The victim met with someone wearing a distinctive red cap.'),
      (26, 78, NULL),
      (27, 134, 'There were unusual movements near dock C around midnight.'),
      (28, 22, NULL),
      (29, 189, 'I saw someone cleaning blood off their hands near the bait shop.'),
      (30, 45, NULL),
      (31, 167, 'A group of men were acting suspiciously near the storage units.'),
      (32, 98, NULL),
      (33, 123, 'The victim received a threatening phone call at the marina office.'),
      (34, 56, NULL),
      (35, 178, 'Someone was taking photos of the victim throughout the day.'),
      (36, 34, NULL),
      (37, 156, 'I noticed a briefcase being passed between two people in the parking lot.'),
      (38, 89, NULL),
      (39, 145, 'There was an unfamiliar yacht docked that disappeared after the incident.'),
      (40, 67, NULL),
      (41, 134, 'The victim seemed distressed after meeting someone near the fuel dock.'),
      (42, 23, NULL),
      (43, 189, 'I overheard a conversation about a deal gone wrong.'),
      (44, 78, NULL),
      (45, 167, 'Someone was watching the marina through binoculars from across the bay.'),
      (46, 45, NULL),
      (47, 123, 'A suspicious package changed hands near the ice machine.'),
      (48, 91, NULL),
      (49, 156, 'The victim was seen arguing with someone on their phone.'),
      (50, 34, NULL),
      (51, 178, 'I saw someone disposing of documents in the marina dumpster.'),
      (52, 67, NULL),
      (53, 145, 'There were unusual diving activities near dock D that night.'),
      (54, 89, NULL),
      (55, 134, 'Someone in a maintenance uniform was acting suspiciously.'),
      (56, 23, NULL),
      (57, 189, 'I heard someone threatening the victim earlier that day.'),
      (58, 56, NULL),
      (59, 167, 'A black SUV was parked at the marina all night without anyone inside.'),
      (60, 78, NULL),
      (61, 123, 'The victim met with multiple people throughout the evening.'),
      (62, 45, NULL),
      (63, 156, 'Someone was seen carrying a heavy bag to their boat late at night.'),
      (64, 91, NULL),
      (65, 145, 'I noticed someone tampering with the victims boat.'),
      (66, 34, NULL),
      (67, 178, 'There was a confrontation near the fish cleaning station.'),
      (68, 67, NULL),
      (69, 134, 'Someone unfamiliar was asking questions about the victim.'),
      (70, 23, NULL),
      (71, 189, 'I saw a flashlight moving around the closed marina office.'),
      (72, 56, NULL),
      (73, 167, 'The security guard was missing from his post during the incident.'),
      (74, 89, NULL),
      (75, 123, 'A mysterious package was delivered to the victims boat.'),
      (76, 78, NULL),
      (77, 156, 'Someone was seen running from the scene carrying a duffel bag.'),
      (78, 45, NULL),
      (79, 145, 'The victim appeared to be following someone earlier that day.'),
      (80, 34, NULL),
      (81, 178, 'I heard a splash followed by a scream near midnight.'),
      (82, 91, NULL),
      (83, 134, 'Someone suspicious was loitering near the victims boat all evening.'),
      (84, 67, NULL),
      (85, 189, 'The victim was seen exchanging envelopes with an unknown person.'),
      (86, 23, NULL),
      (87, 167, 'A boat left the marina without proper lighting after hours.'),
      (88, 56, NULL),
      (89, 123, 'I saw someone wearing gloves despite the warm weather.'),
      (90, 78, NULL),
      (91, 156, 'The victim had an intense discussion near the fuel pumps.'),
      (92, 45, NULL),
      (93, 145, 'Someone unfamiliar was watching the marina from their car.'),
      (94, 89, NULL),
      (95, 134, 'I noticed someone signaling with a flashlight from their boat.'),
      (96, 34, NULL),
      (97, 178, 'The victim received a suspicious package earlier that day.'),
      (98, 67, NULL),
      (99, 189, 'Someone was seen climbing onto boats after hours.'),
      (100, 23, NULL),
      (101, 101, 'I saw someone check into a hotel on August 13. The guy looked nervous.'),
      (102, 58, NULL),
      (103, 102, 'I heard someone checked into a hotel with "Sunset" in the name.'),
      (104, 58, NULL),
      (105, 104, 'I just mind my business, detective.'),
      (106, 58, NULL),
      (107, 105, 'I didn’t do anything. Ask Raul. He knows more.'),
      (108, 58, NULL),
      (109, 106, 'A boat engine was running unusually late that night.'),
      (110, 58, NULL),
      (111, 7, 'Someone was taking photos of the marina security cameras.'),
      (112, 58, NULL),
      (113, 8, 'I saw a person in dark clothes sneaking around the docks.'),
      (114, 58, NULL),
      (115, 9, 'There was an argument near slip 42 around sunset.'),
      (116, 58, NULL),
      (117, 10, 'A speedboat left the marina at high speed after midnight.'),
      (118, 58, NULL),
      (119, 11, 'Someone disabled the dock lights in section C.'),
      (120, 58, NULL),
      (121, 12, 'I heard breaking glass coming from the marina office.'),
      (122, 58, NULL),
      (123, 13, 'A suspicious package changed hands near the fuel dock.'),
      (124, 58, NULL),
      (125, 14, 'Multiple people were seen entering the victims boat.'),
      (126, 58, NULL),
      (127, 15, 'Someone tampered with the security cameras.'),
      (128, 58, NULL),
      (129, 16, 'A duffel bag was thrown into the water late at night.'),
      (130, 58, NULL),
      (131, 17, 'The victim seemed agitated during a phone call.'),
      (132, 58, NULL),
      (133, 18, 'Strange lights were seen from an anchored boat.'),
      (134, 58, NULL),
      (135, 19, 'Someone was searching the victims car in the parking lot.'),
      (136, 58, NULL),
      (137, 20, 'A heated argument broke out near the bait shop.'),
      (138, 58, NULL),
      (139, 21, 'Multiple boats left the marina without proper clearance.'),
      (140, 58, NULL),
      (141, 22, 'Someone was seen cleaning unusual stains from their deck.'),
      (142, 58, NULL),
      (143, 23, 'A suspicious meeting took place near the ice machine.'),
      (144, 58, NULL),
      (145, 24, 'The victim received several threatening phone calls.'),
      (146, 58, NULL),
      (147, 25, 'Someone broke into the harbormasters office.'),
      (148, 58, NULL),
      (149, 26, 'A briefcase was exchanged near dock B.'),
      (150, 58, NULL),
      (151, 27, 'Unusual activity was spotted on the security feeds.'),
      (152, 58, NULL),
      (153, 28, 'Someone disabled the docks security system.'),
      (154, 58, NULL),
      (155, 29, 'A boat was hastily cleaned in the early morning.'),
      (156, 58, NULL),
      (157, 30, 'Multiple people fled the scene after the incident.'),
      (158, 58, NULL),
      (159, 31, 'The victim met with someone in a black suit.'),
      (160, 58, NULL),
      (161, 32, 'Strange noises were heard from the storage area.'),
      (162, 58, NULL),
      (163, 33, 'Someone tampered with the victims boat engine.'),
      (164, 58, NULL),
      (165, 34, 'A suspicious vehicle circled the marina repeatedly.'),
      (166, 58, NULL),
      (167, 35, 'Multiple people were seen running from the crime scene.'),
      (168, 58, NULL),
      (169, 36, 'Someone disposed of evidence in the dumpster.'),
      (170, 58, NULL),
      (171, 37, 'The security cameras were deliberately turned off.'),
      (172, 58, NULL),
      (173, 38, 'A confrontation occurred near the fish cleaning station.'),
      (174, 58, NULL),
      (175, 39, 'Someone accessed the marina after hours.'),
      (176, 58, NULL),
      (177, 40, 'The victim appeared distressed before the incident.'),
      (178, 58, NULL),
      (179, 41, 'Multiple boats were damaged that night.'),
      (180, 58, NULL),
      (181, 42, 'Someone was seen wearing suspicious clothing.'),
      (182, 58, NULL),
      (183, 43, 'A group of people gathered suspiciously near dock C.'),
      (184, 58, NULL),
      (185, 44, 'The victim had an altercation with an unknown person.'),
      (186, 58, NULL),
      (187, 45, 'Someone tampered with the surveillance equipment.'),
      (188, 58, NULL),
      (189, 46, 'Multiple witnesses reported unusual activity.'),
      (190, 58, NULL),
      (191, 47, 'A suspicious package was found floating in the water.'),
      (192, 58, NULL),
      (193, 48, 'Someone made threatening gestures toward the victim.'),
      (194, 58, NULL),
      (195, 49, 'The dock lights were mysteriously disabled.'),
      (196, 58, NULL),
      (197, 50, 'A boat left without proper documentation.'),
      (198, 58, NULL),
      (199, 51, 'Strange sounds were heard from the marina office.'),
      (200, 58, NULL),
      (201, 52, 'Multiple people were involved in a suspicious exchange.'),
      (202, 58, NULL),
      (203, 53, 'Someone was seen carrying unusual equipment.'),
      (204, 58, NULL),
      (205, 54, 'The victim received a mysterious package.'),
      (206, 58, NULL),
      (207, 55, 'A heated argument occurred before the incident.'),
      (208, 58, NULL)
    ;`,

  // 4. Hotel Check-ins Table
  `CREATE TABLE hotel_checkins (
      id INTEGER PRIMARY KEY,
      person_id INTEGER,
      hotel_name TEXT,
      check_in_date INTEGER,
      FOREIGN KEY (person_id) REFERENCES person(id)
    );`,
  `INSERT INTO hotel_checkins (id, person_id, hotel_name, check_in_date) VALUES
      (1, 6, 'Sunset Inn', 19860813),
      (2, 7, 'Sunset Marina Hotel', 19860813),
      (3, 8, 'Sunset Palm Resort', 19860813),
      (4, 9, 'Palm Breeze Hotel', 19860812),
      (5, 10, 'Blue Wave Hotel', 19860813)
    ;`,

  // 5. Surveillance Records Table (Used to further filter hotel check-ins)
  `CREATE TABLE surveillance_records (
      id INTEGER PRIMARY KEY,
      person_id INTEGER,
      hotel_id INTEGER,
      suspicious_activity TEXT,
      FOREIGN KEY (person_id) REFERENCES person(id),
      FOREIGN KEY (hotel_id) REFERENCES hotel_checkins(id)
    );`,
  `INSERT INTO surveillance_records (id, person_id, hotel_id, suspicious_activity) VALUES
      (1, 6, 1, 'Spotted entering late at night.'),
      (2, 7, 2, 'Seen arguing with an unknown individual.'),
      (3, 8, 3, 'Left the hotel suddenly at 3 AM.'),
      (4, 9, 4, 'No suspicious activity recorded.'),
      (5, 10, 5, 'Drunk and disorderly conduct.')
    ;`,

  // 6. Final Interviews Table
  `CREATE TABLE confessions (
      id INTEGER PRIMARY KEY,
      person_id INTEGER,
      confession TEXT,
      FOREIGN KEY (person_id) REFERENCES person(id)
    );`,
  `INSERT INTO confessions (id, person_id, confession) VALUES
      (1, 6, 'I don’t know anything about this.'),
      (2, 7, 'I just handled the money. I didn’t kill anyone.'),
      (3, 8, 'Alright! Alright! I did it. I was paid to make sure he never left the marina alive.')
    ;`,
];
