export default [
  // Create and populate the crime_scene table
  `CREATE TABLE crime_scene (
      id INTEGER PRIMARY KEY,
      date INTEGER,
      type TEXT,
      location TEXT,
      description TEXT
    );`,
  `INSERT INTO crime_scene (id, date, type, location, description) VALUES
      (1, 20120909, 'theft', 'City Street', 'A guest was found dead in their hotel room. There were signs of a struggle and blood near the bed.'),
      (2, 19920415, 'theft', 'Downtown Bank', 'A briefcase was stolen during a robbery. A man in a suit was seen leaving the premises with it.'),
      (3, 20010702, 'murder', 'Corner Café', 'A body was found behind the café. No witnesses reported anything, but there was a knife wound in the back.'),
      (4, 19980328, 'bribery', 'Metro Station', NULL),
      (5, 20091113, 'theft', 'Park Avenue Office', 'A briefcase with classified documents was stolen. A witness mentioned a person in a blazer running away from the scene.'),
      (6, 20050716, 'murder', 'Grand Hotel', 'A guest was found dead in their room with signs of foul play. The door was locked from the inside, and there was no sign of forced entry.'),
      (7, 19960205, 'theft', 'City Library', 'A briefcase containing confidential papers went missing. The thief was caught on security camera, wearing a jacket.'),
      (8, 20080422, 'bribery', 'Main Street Mall', NULL),
      (9, 20110630, 'theft', 'Old Town Square', 'A man was seen fleeing with a briefcase. He had a scar on his right hand and was wearing a coat.'),
      (10, 20031218, 'murder', 'Central Park', 'A woman’s body was discovered in the park with signs of strangulation. A witness saw a man wearing a baseball cap near the scene.'),
      (11, 20120909, 'theft', 'City Museum', 'A briefcase containing valuable artifacts was taken. A man in a trench coat was seen leaving the scene.'),
      (12, 20140512, 'theft', 'Airport Terminal', NULL),
      (13, 19950521, 'murder', 'Museum of Modern Art', 'A prominent artist was found dead in his studio with multiple stab wounds. No suspect has been identified yet.'),
      (14, 20060907, 'theft', 'Luxury Hotel', 'A briefcase was stolen from a guest. The thief was wearing a dark suit and had a scar on his right cheek.'),
      (15, 19980211, 'theft', 'Subway Station', 'A briefcase went missing from the platform. A man in a leather jacket was seen with it.'),
      (16, 20021225, 'bribery', 'Downtown Restaurant', NULL),
      (17, 20160114, 'murder', 'University Library', 'A student was found dead near the library’s entrance. The cause of death was a gunshot wound to the head.'),
      (18, 19910730, 'theft', 'Art Gallery', NULL),
      (19, 20050710, 'murder', 'Beachside Hotel', 'A guest was found dead in their hotel room. There were signs of a struggle and blood near the bed.'),
      (20, 19990416, 'theft', 'City Plaza', 'A briefcase went missing after an event. No clear suspect was identified, but a man in a gray coat was seen near the area.'),
      (21, 20080312, 'theft', 'Luxury Mall', 'A briefcase with valuable goods was stolen. The thief was described as wearing a dark jacket and had a visible scar.'),
      (22, 20100122, 'bribery', 'Highway Rest Stop', NULL),
      (23, 20151203, 'murder', 'Coffee Shop', 'A barista was found dead behind the counter with a gunshot wound. The suspect was seen leaving in a red car.'),
      (24, 20180418, 'bribery', 'City Hall', 'A corrupt city official was caught accepting a bribe. A videotape showed the transaction in a private office.'),
      (25, 20120719, 'theft', 'Warehouse District', NULL),
      (26, 19980903, 'murder', 'Luxury Condo', 'A body was discovered in a high-rise apartment. The victim had multiple gunshot wounds.'),
      (27, 20060522, 'theft', 'Shopping Mall', 'A purse was stolen from a woman’s bag in the food court. A man in a red hoodie was seen near the area.'),
      (28, 19941030, 'bribery', 'Corporate Office', 'A CEO was seen accepting illegal payments from a contractor. The contract was later canceled under suspicious circumstances.'),
      (29, 20150914, 'theft', 'Train Station', NULL),
      (30, 20070426, 'bribery', 'Golf Club', 'A bribery scandal involving several high-ranking officials at the country club. A video surfaced showing the exchange of money.'),
      (31, 20010212, 'murder', 'Dark Alley', 'A man was found dead in a dark alley with a knife stuck in his chest. No suspects yet.'),
      (32, 20180125, 'theft', 'Bank Vault', 'A bank vault was broken into overnight. Security cameras were tampered with, and the culprit remains unidentified.'),
      (33, 19961118, 'murder', 'Luxury Yacht', NULL),
      (34, 20030705, 'bribery', 'Subway Station', 'A bribe was offered to a transit officer in exchange for bypassing the fare. The officer reported the incident immediately.'),
      (35, 19921221, 'theft', 'Fashion Boutique', 'A necklace worth thousands was stolen during a fashion show. A woman was seen leaving with it in her purse.'),
      (36, 20081008, 'murder', 'City Park', 'A body was discovered in the park. The victim was hit by a car, and police are investigating whether it was intentional.'),
      (37, 20150203, 'theft', 'Corporate Office', 'A laptop containing company secrets was stolen from a secured office. No signs of forced entry.'),
      (38, 19950627, 'theft', 'Luxury Mall', 'A designer handbag was stolen from a display. A suspect in a suit was seen on the surveillance footage.'),
      (39, 20030410, 'bribery', 'Construction Site', 'A contractor was bribed to overlook safety violations. The transaction was caught on camera.'),
      (40, 20091206, 'theft', 'Parking Garage', 'A car was stolen from a parking garage. Security footage shows a person in a hoodie breaking into the vehicle.'),
      (41, 20150722, 'murder', 'Street Corner', 'A young man was found dead near a busy street. Police are investigating the cause of death, possibly drug-related.'),
      (42, 19980305, 'theft', 'Shopping Mall', 'A briefcase containing cash was stolen from a display. A suspect in a red jacket was seen near the scene.'),
      (43, 20060119, 'bribery', 'Airport Lounge', 'A flight attendant was caught accepting a bribe to let passengers bypass security checks.'),
      (44, 20171003, 'theft', 'Car Dealership', NULL),
      (45, 20080409, 'murder', 'Night Club', 'A man was found dead in the club’s bathroom. Police are investigating whether it was a drug deal gone wrong.'),
      (46, 20140822, 'bribery', 'Public Office', 'A city official was caught accepting bribes from contractors in exchange for government contracts.'),
      (47, 20031014, 'murder', 'Back Alley', 'A woman was found dead with a broken neck. No witnesses were present, and no suspects have been identified.'),
      (48, 20151209, 'theft', 'Restaurant', 'A woman’s purse was stolen while she was dining. A man in a black jacket was seen near the table.'),
      (49, 19990217, 'bribery', 'Government Building', 'A politician was caught receiving bribes from a lobbyist. The deal was overheard by a security guard.'),
      (50, 20100115, 'theft', 'Jewelry Store', 'A diamond ring was stolen from a high-end jewelry store. The thief was wearing a black coat and gloves.'),
      (51, 20090222, 'bribery', 'Courtroom', NULL),
      (52, 20061214, 'murder', 'Luxury Hotel', 'A businessman was found dead in his hotel room. Police suspect foul play, but no suspects have been named yet.'),
      (53, 19980718, 'theft', 'Art Gallery', 'A valuable painting was stolen during an exhibition. A woman in a red dress was seen leaving the gallery.'),
      (54, 20080304, 'bribery', 'Construction Site', NULL),
      (55, 19971005, 'murder', 'City Hospital', 'A nurse was found dead in a hospital storage room. The police are looking into hospital staff for possible involvement.'),
      (56, 20011117, 'bribery', 'Financial District', 'A stockbroker was caught bribing clients to inflate their investments.'),
      (57, 20070315, 'theft', 'Corporate Office', 'A company laptop with sensitive information was stolen. A man in a suit was seen leaving the office with it.'),
      (58, 20130321, 'murder', 'City Street', NULL),
      (59, 20141011, 'theft', 'Airport Terminal', 'A passenger’s suitcase was swapped with another at the terminal. The suspect was wearing a red shirt.'),
      (60, 20100518, 'bribery', 'Public Office', 'An official was caught accepting bribes to approve a construction project without proper inspection.'),
      (61, 19941122, 'murder', 'City Bar', 'A man was found dead after an altercation in a local bar. The suspect fled the scene.'),
      (62, 20050329, 'theft', 'Luxury Mall', 'A woman’s handbag was stolen from a high-end store. A man in a gray jacket was seen walking away with it.'),
      (63, 20170704, 'murder', 'Restaurant', 'A chef was found dead in the kitchen. No obvious injuries, but foul play is suspected.'),
      (64, 20020301, 'bribery', 'Construction Site', 'A contractor was bribed to overlook safety violations on a new building project.'),
      (65, 20061103, 'theft', 'Public Library', 'A library card with personal information was stolen from the librarian’s desk. A suspect was seen leaving with it.'),
      (66, 20121118, 'theft', 'Casino', 'A man was seen taking chips from an unguarded table. The suspect was wearing a black hoodie.'),
      (67, 19990514, 'murder', 'City Park', 'A body was discovered near the park bench. The cause of death was a gunshot wound.'),
      (68, 20190906, 'bribery', 'University', 'A professor was caught accepting bribes from students in exchange for better grades.'),
      (69, 20071220, 'theft', 'Train Station', 'A man stole a suitcase from a passenger at the train station. The suspect was wearing a jacket and hat.'),
      (70, 19990410, 'murder', 'Street Corner', NULL),
      (71, 20080111, 'theft', 'Restaurant', 'A purse was stolen while the victim was eating dinner. The suspect was seen walking away briskly.'),
      (72, 20180228, 'bribery', 'Municipal Office', 'A city official was seen accepting cash from a local contractor to fast-track his projects.'),
      (73, 20030504, 'theft', 'Library', 'A rare book was stolen from the library. The suspect was seen entering and exiting the restricted area.'),
      (74, 20160622, 'murder', 'Downtown Alley', 'A woman was found dead in an alley with signs of blunt force trauma to her head.'),
      (75, 19930310, 'theft', 'Parking Lot', NULL),
      (76, 19851120, 'theft', 'Blue Note Lounge', 'A briefcase containing sensitive documents vanished. A witness reported a man in a trench coat with a scar on his left cheek fleeing the scene.'),
      (77, 20151019, 'murder', 'Office Building', 'A manager was found dead in his office. Police suspect a workplace dispute may have led to the murder.'),
      (78, 20110225, 'theft', 'Art Auction', 'A painting was stolen during an auction. The thief was seen fleeing the scene.'),
      (79, 19980507, 'bribery', 'Medical Center', NULL),
      (80, 20091229, 'theft', 'Airport Security', 'A bag containing valuable items was stolen during security checks.'),
      (81, 19941021, 'murder', 'Rooftop Bar', 'A man was found dead after an argument with another patron. No weapons were found at the scene.'),
      (82, 20081116, 'theft', 'Corporate Office', 'A laptop with confidential information was stolen. No signs of forced entry, but a suspect in a suit was seen.'),
      (83, 20030613, 'bribery', 'Hospital', 'A doctor was caught accepting money to provide fake medical reports for insurance claims.'),
      (84, 20150607, 'murder', 'Woods', 'A body was discovered in the woods with a bullet wound to the chest. The police are still looking for suspects.'),
      (85, 20081005, 'theft', 'Shopping Mall', 'A wallet was stolen from a shopper. The thief was caught on camera wearing a baseball cap.'),
      (86, 20131011, 'bribery', 'City Council', 'A councilman was caught accepting bribes to approve zoning laws.'),
      (87, 20180503, 'theft', 'Luxury Store', 'A man was seen taking a bracelet without paying for it.'),
      (88, 19921214, 'murder', 'Train Station', 'A body was found near the tracks. Investigators believe it may have been an accident or foul play.'),
      (89, 20070911, 'bribery', 'Corporate Office', NULL),
      (90, 20140206, 'theft', 'Tech Conference', 'A laptop was stolen during the conference. A man in a black hoodie was seen leaving the area.'),
      (91, 20100817, 'theft', 'Bookstore', 'A rare edition book was stolen from a bookstore display.'),
      (92, 19970103, 'bribery', 'Police Station', 'A police officer was caught accepting bribes from local criminals to overlook their activities.'),
      (93, 20091129, 'murder', 'House', 'A body was found in a house with signs of strangulation.'),
      (94, 19960521, 'theft', 'Gallery', 'A painting was stolen during an exhibition.'),
      (95, 20131028, 'bribery', 'Post Office', 'A postal worker was caught accepting money to tamper with mail.'),
      (96, 20080303, 'murder', 'Lakeside', NULL),
      (97, 20030512, 'theft', 'Gas Station', 'A cashier was robbed at gunpoint. The thief took the cash from the register.'),
      (98, 20150717, 'bribery', 'School', 'A teacher was caught accepting bribes from parents to give their children better grades.'),
      (99, 20090611, 'theft', 'Construction Site', 'A truck full of equipment was stolen from a construction site.'),
      (100, 20180320, 'murder', 'Club', 'A man was killed during a fight inside a club. The suspect was seen leaving the scene.')
    ;`,

  // Create and populate the suspects table
  `CREATE TABLE suspects (
      id INTEGER PRIMARY KEY,
      name TEXT,
      attire TEXT,
      scar TEXT
    );`,
  `INSERT INTO suspects (id, name, attire, scar) VALUES
      (1, 'Michael Johnson', 'none', 'none'),
      (2, 'Tony DeMarco', 'suit', 'none'),
      (3, 'Frankie Lombardi', 'trench coat', 'left cheek'),
      (4, 'Carlos Garcia', 'jacket', 'right arm'),
      (5, 'Marko Shvets', 't-shirt', 'none'),
      (6, 'Amanda Taylor', 'blouse', 'right leg'),
      (7, 'Richard Brown', 'tuxedo', 'none'),
      (8, 'Heather Williams', 'dress', 'left hand'),
      (9, 'Joshua Smith', 'suit', 'none'),
      (10, 'Claire Green', 'cardigan', 'none'),
      (11, 'Evan Davis', 'sweater', 'right shoulder'),
      (12, 'Nina Patel', 'skirt', 'left arm'),
      (13, 'Sam Johnson', 'jacket', 'none'),
      (14, 'Maya Nguyen', 't-shirt', 'none'),
      (15, 'Daniel King', 'blazer', 'left thigh'),
      (16, 'Laura Wright', 'suit', 'none'),
      (17, 'Chris Scott', 'hoodie', 'right wrist'),
      (18, 'Sophie Harris', 'sweater', 'left foot'),
      (19, 'Tommy Walker', 'tuxedo', 'none'),
      (20, 'Ava Lewis', 'dress', 'left knee'),
      (21, 'Victor Carter', 'suit', 'none'),
      (22, 'Mason Clark', 'jacket', 'left ear'),
      (23, 'Zoe Mitchell', 'cardigan', 'none'),
      (24, 'Oliver Hall', 'sweater', 'none'),
      (25, 'Ellie Anderson', 't-shirt', 'right foot'),
      (26, 'Andrew Moore', 'blazer', 'right cheek'),
      (27, 'Penny Turner', 'suit', 'none'),
      (28, 'Benjamin Lopez', 'jacket', 'none'),
      (29, 'Sophia Martin', 'dress', 'left shoulder'),
      (30, 'Matthew Collins', 'tuxedo', 'none'),
      (31, 'Emily Adams', 'hoodie', 'none'),
      (32, 'Lucas Stewart', 'blouse', 'none'),
      (33, 'Chloe Baker', 'skirt', 'none'),
      (34, 'Liam Mitchell', 't-shirt', 'left wrist'),
      (35, 'Charlotte White', 'blazer', 'none'),
      (36, 'James Young', 'cardigan', 'right leg'),
      (37, 'Ella King', 'suit', 'none'),
      (38, 'Lucas Scott', 'jacket', 'left cheek'),
      (39, 'Aiden Gonzalez', 'hoodie', 'none'),
      (40, 'Amelia Green', 'dress', 'left wrist'),
      (41, 'William Johnson', 'tuxedo', 'none'),
      (42, 'Mila Roberts', 'sweater', 'right hand'),
      (43, 'Jackson Mitchell', 'blazer', 'none'),
      (44, 'Grace Moore', 't-shirt', 'right knee'),
      (45, 'John Lee', 'cardigan', 'none'),
      (46, 'Lily Jackson', 'jacket', 'none'),
      (47, 'Daniel Taylor', 'hoodie', 'none'),
      (48, 'Sophie Harris', 'blazer', 'none'),
      (49, 'Benjamin White', 'suit', 'none'),
      (50, 'Dylan Walker', 'tuxedo', 'none'),
      (51, 'Gabriella Cooper', 'sweater', 'none'),
      (52, 'Sebastian Smith', 'jacket', 'left hand'),
      (53, 'Sophie Jones', 'cardigan', 'none'),
      (54, 'Ethan Brown', 't-shirt', 'right shoulder'),
      (55, 'Elijah Johnson', 'hoodie', 'none'),
      (56, 'Charlotte Robinson', 'blazer', 'none'),
      (57, 'Maddison Lewis', 'suit', 'none'),
      (58, 'Alexander Campbell', 'dress', 'left knee'),
      (59, 'Mia Cooper', 'skirt', 'right arm'),
      (60, 'Ethan Carter', 'blouse', 'none'),
      (61, 'Sophia Harris', 'jacket', 'left thigh'),
      (62, 'Grace Scott', 'blazer', 'none'),
      (63, 'Benjamin Miller', 'suit', 'right cheek'),
      (64, 'Madeline Taylor', 'sweater', 'none'),
      (65, 'Olivia Young', 't-shirt', 'none'),
      (66, 'Jack Mitchell', 'jacket', 'right wrist'),
      (67, 'Isabella Wilson', 'dress', 'left arm'),
      (68, 'Aiden Turner', 'blouse', 'right leg'),
      (69, 'Aria Morgan', 'sweater', 'none'),
      (70, 'Ryan Nelson', 'hoodie', 'left knee'),
      (71, 'Lily White', 'suit', 'none'),
      (72, 'James Carter', 'cardigan', 'none'),
      (73, 'Chloe Anderson', 'tuxedo', 'none'),
      (74, 'Ava Moore', 'blazer', 'none'),
      (75, 'Michael Scott', 'dress', 'left cheek'),
      (76, 'Emma Hall', 'jacket', 'none'),
      (77, 'David Davis', 'sweater', 'right hand'),
      (78, 'Lucas White', 't-shirt', 'left wrist'),
      (79, 'Lily Smith', 'hoodie', 'none'),
      (80, 'Mason Turner', 'blazer', 'right knee'),
      (81, 'Matthew Jackson', 'suit', 'none'),
      (82, 'Sophie Robinson', 'cardigan', 'none'),
      (83, 'Isaac Martin', 'jacket', 'none'),
      (84, 'Maya Green', 'sweater', 'left hand'),
      (85, 'James Lee', 't-shirt', 'right cheek'),
      (86, 'Jack Robinson', 'blazer', 'none'),
      (87, 'Olivia Walker', 'dress', 'none'),
      (88, 'Ella Cooper', 'sweater', 'right wrist'),
      (89, 'Liam Davis', 'blouse', 'none'),
      (90, 'Oliver Harris', 'cardigan', 'none'),
      (91, 'Charlotte King', 'jacket', 'none'),
      (92, 'David Young', 'suit', 'none'),
      (93, 'Sebastian Lewis', 'tuxedo', 'none'),
      (94, 'Emma Carter', 'dress', 'none'),
      (95, 'Maxwell Taylor', 'jacket', 'left ear'),
      (96, 'Benjamin White', 'hoodie', 'none'),
      (97, 'Chloe Lee', 'blazer', 'none'),
      (98, 'Amelia Walker', 't-shirt', 'none'),
      (99, 'Dylan Lewis', 'blouse', 'right leg'),
      (100, 'Ryan Green', 'cardigan', 'none'),
      (101, 'Sophie Turner', 'suit', 'none'),
      (102, 'Lucas Scott', 'sweater', 'left wrist'),
      (103, 'Maddison Carter', 'jacket', 'right shoulder'),
      (104, 'Jackson Brown', 'blazer', 'none'),
      (105, 'Victoria Cooper', 'dress', 'none'),
      (106, 'Evan Lewis', 't-shirt', 'none'),
      (107, 'David Wilson', 'blouse', 'left cheek'),
      (108, 'Sophia Green', 'cardigan', 'none'),
      (109, 'Charlotte Harris', 'jacket', 'none'),
      (110, 'Oliver Carter', 'sweater', 'right hand'),
      (111, 'Emily Taylor', 'tuxedo', 'none'),
      (112, 'John White', 'blazer', 'none'),
      (113, 'Amelia Brown', 'hoodie', 'none'),
      (114, 'Lucas Moore', 'dress', 'left knee'),
      (115, 'David Cooper', 'suit', 'none'),
      (116, 'Oliver Harris', 't-shirt', 'none'),
      (117, 'Maya Walker', 'cardigan', 'right foot'),
      (118, 'Sophia Green', 'blouse', 'none'),
      (119, 'James Taylor', 'sweater', 'none'),
      (120, 'Mason Brown', 'jacket', 'none'),
      (121, 'Olivia King', 't-shirt', 'left thigh'),
      (122, 'Charlotte White', 'hoodie', 'none'),
      (123, 'Mia Davis', 'dress', 'none'),
      (124, 'Maddison Turner', 'jacket', 'right wrist'),
      (125, 'Isabella Martin', 'suit', 'none'),
      (126, 'Benjamin White', 'blazer', 'none'),
      (127, 'David Lewis', 'sweater', 'none'),
      (128, 'Sophie Green', 'cardigan', 'left cheek'),
      (129, 'Liam Martin', 'tuxedo', 'none'),
      (130, 'Ella Turner', 'jacket', 'none'),
      (131, 'Chloe King', 't-shirt', 'right foot'),
      (132, 'Sebastian Walker', 'blouse', 'none'),
      (133, 'Olivia White', 'suit', 'none'),
      (134, 'Mason Turner', 'dress', 'none'),
      (135, 'Victor Brown', 'sweater', 'none'),
      (136, 'Benjamin Harris', 'blazer', 'none'),
      (137, 'Isabella Davis', 't-shirt', 'none'),
      (138, 'Mia Green', 'cardigan', 'right arm'),
      (139, 'Liam Brown', 'jacket', 'none'),
      (140, 'Emily White', 'sweater', 'none'),
      (141, 'Olivia Turner', 'tuxedo', 'none'),
      (142, 'David King', 'blazer', 'none'),
      (143, 'Matthew Scott', 'sweater', 'right shoulder'),
      (144, 'Isabella White', 'dress', 'none'),
      (145, 'Aiden Harris', 'cardigan', 'none'),
      (146, 'Benjamin Green', 'jacket', 'none'),
      (147, 'Sophia Turner', 'hoodie', 'none'),
      (148, 'Oliver Harris', 't-shirt', 'none'),
      (149, 'Ethan King', 'blazer', 'none'),
      (150, 'Chloe Brown', 'cardigan', 'none'),
      (151, 'Zoe Taylor', 'jacket', 'none'),
      (152, 'Lucas Carter', 'blouse', 'none'),
      (153, 'Sophia Martin', 'suit', 'none'),
      (154, 'Mason Lee', 't-shirt', 'none'),
      (155, 'Olivia White', 'cardigan', 'none'),
      (156, 'Benjamin Scott', 'hoodie', 'none'),
      (157, 'Chloe Davis', 'dress', 'none'),
      (158, 'Liam Young', 'sweater', 'none'),
      (159, 'David Green', 'blazer', 'none'),
      (160, 'Ethan Taylor', 'jacket', 'none'),
      (161, 'Olivia King', 'tuxedo', 'none'),
      (162, 'Sophie Harris', 'sweater', 'none'),
      (163, 'Lily Brown', 'cardigan', 'none'),
      (164, 'Benjamin Walker', 'suit', 'none'),
      (165, 'Matthew Davis', 't-shirt', 'none'),
      (166, 'Victor Young', 'jacket', 'none'),
      (167, 'Isabella White', 'blouse', 'none'),
      (168, 'David Brown', 'sweater', 'none'),
      (169, 'Chloe Walker', 'cardigan', 'none'),
      (170, 'Olivia Green', 'tuxedo', 'none'),
      (171, 'Zoe Harris', 'dress', 'none'),
      (172, 'Liam White', 'suit', 'none'),
      (173, 'Benjamin Carter', 'sweater', 'none'),
      (174, 'Sophie Turner', 'jacket', 'none'),
      (175, 'Lucas Brown', 'blouse', 'none'),
      (176, 'Mason White', 't-shirt', 'none'),
      (177, 'David Harris', 'cardigan', 'none'),
      (178, 'Olivia King', 'dress', 'none'),
      (179, 'Liam Turner', 'blazer', 'none'),
      (180, 'Sophie Davis', 'hoodie', 'none'),
      (181, 'Victor Green', 'tuxedo', 'none'),
      (182, 'Sophia Taylor', 'sweater', 'none'),
      (183, 'Vincent Malone', 'trench coat', 'left cheek'),
      (184, 'Benjamin Young', 'blouse', 'none'),
      (185, 'Olivia White', 'cardigan', 'none'),
      (186, 'Mason Davis', 'suit', 'none'),
      (187, 'David King', 't-shirt', 'none'),
      (188, 'Chloe Brown', 'jacket', 'none'),
      (189, 'Victor Harris', 'hoodie', 'none'),
      (190, 'Sophie King', 'blouse', 'none'),
      (191, 'Olivia Green', 'tuxedo', 'none'),
      (192, 'Isabella Walker', 'dress', 'none'),
      (193, 'Benjamin White', 'cardigan', 'none'),
      (194, 'Ethan Turner', 'sweater', 'none'),
      (195, 'David Brown', 'jacket', 'none'),
      (196, 'Chloe Walker', 'blouse', 'none'),
      (197, 'Liam Davis', 't-shirt', 'none'),
      (198, 'Olivia White', 'suit', 'none'),
      (199, 'Victor Green', 'cardigan', 'none'),
      (200, 'Sophie Taylor', 'blazer', 'none'),
      (201, 'Mason Walker', 'tuxedo', 'none'),
      (202, 'David White', 'sweater', 'none'),
      (203, 'Olivia Brown', 'jacket', 'none'),
      (204, 'Zoe King', 'blouse', 'none'),
      (205, 'Liam Young', 'cardigan', 'none'),
      (206, 'Sophie Green', 'suit', 'none'),
      (207, 'Victor White', 't-shirt', 'none'),
      (208, 'Olivia Davis', 'blazer', 'none'),
      (209, 'Lucas Brown', 'hoodie', 'none'),
      (210, 'David Harris', 'jacket', 'none'),
      (211, 'Sophie Turner', 'sweater', 'none'),
      (212, 'Isabella King', 'blouse', 'none'),
      (213, 'Benjamin Green', 'cardigan', 'none'),
      (214, 'Ethan Davis', 'tuxedo', 'none'),
      (215, 'Victor Brown', 'suit', 'none'),
      (216, 'Lily White', 'jacket', 'none'),
      (217, 'Mason King', 't-shirt', 'none'),
      (218, 'David Taylor', 'blazer', 'none'),
      (219, 'Olivia Walker', 'hoodie', 'none'),
      (220, 'Lucas Davis', 'sweater', 'none'),
      (221, 'Zoe Brown', 'cardigan', 'none'),
      (222, 'Sophia Taylor', 'blouse', 'none'),
      (223, 'Victor Walker', 'jacket', 'none'),
      (224, 'Mason Green', 't-shirt', 'none'),
      (225, 'Ethan Brown', 'blazer', 'none'),
      (226, 'David Harris', 'dress', 'none'),
      (227, 'Olivia Walker', 'suit', 'none'),
      (228, 'Zoe Taylor', 'hoodie', 'none'),
      (229, 'Lucas Green', 'cardigan', 'none'),
      (230, 'Victor King', 'blouse', 'none'),
      (231, 'Isabella Harris', 'suit', 'none'),
      (232, 'Benjamin Green', 'jacket', 'none'),
      (233, 'Olivia Brown', 't-shirt', 'none'),
      (234, 'David Walker', 'hoodie', 'none'),
      (235, 'Victor Davis', 'blazer', 'none'),
      (236, 'Sophie King', 'dress', 'none'),
      (237, 'Christopher Black', 'trench coat', 'right cheek'),
      (238, 'Mason Taylor', 'sweater', 'none'),
      (239, 'Olivia Green', 'cardigan', 'none'),
      (240, 'Victor Brown', 'blouse', 'none'),
      (241, 'Liam White', 't-shirt', 'none'),
      (242, 'Ethan King', 'suit', 'none'),
      (243, 'Sophia Brown', 'hoodie', 'none'),
      (244, 'Olivia Taylor', 'blazer', 'none'),
      (245, 'David Walker', 'jacket', 'none'),
      (246, 'Benjamin Green', 'cardigan', 'none'),
      (247, 'Victor White', 't-shirt', 'none'),
      (248, 'Zoe Brown', 'blouse', 'none'),
      (249, 'Lucas Green', 'suit', 'none'),
      (250, 'Mason King', 'hoodie', 'none'),
      (251, 'David Brown', 'suit', 'none'),
      (252, 'Olivia Green', 'blazer', 'left leg'),
      (253, 'Victor Taylor', 'jacket', 'none'),
      (254, 'Mason Walker', 'blouse', 'none'),
      (255, 'Zoe Harris', 'sweater', 'none'),
      (256, 'Isabella Brown', 'cardigan', 'none'),
      (257, 'Ethan Green', 't-shirt', 'left cheek'),
      (258, 'Sophie White', 'hoodie', 'none'),
      (259, 'Olivia Brown', 'dress', 'none'),
      (260, 'David King', 'blazer', 'none'),
      (261, 'Zoe Green', 'suit', 'none'),
      (262, 'Mason White', 't-shirt', 'none'),
      (263, 'Benjamin Walker', 'jacket', 'right hand'),
      (264, 'Olivia Brown', 'hoodie', 'none'),
      (265, 'Victor Green', 'sweater', 'left knee'),
      (266, 'Sophie Harris', 'tuxedo', 'none'),
      (267, 'Isabella Brown', 'dress', 'none'),
      (268, 'Mason King', 'blouse', 'right foot'),
      (269, 'Zoe White', 'cardigan', 'none'),
      (270, 'David Taylor', 'jacket', 'none'),
      (271, 'Lucas Green', 't-shirt', 'left wrist'),
      (272, 'Victor Brown', 'suit', 'none'),
      (273, 'Benjamin White', 'blazer', 'none'),
      (274, 'Isabella Harris', 'sweater', 'none'),
      (275, 'Sophie Brown', 'jacket', 'none'),
      (276, 'Olivia Green', 't-shirt', 'none'),
      (277, 'David White', 'blouse', 'none'),
      (278, 'Victor Taylor', 'suit', 'none'),
      (279, 'Liam Green', 'cardigan', 'none'),
      (280, 'Mason Brown', 'hoodie', 'none'),
      (281, 'Sophia White', 'dress', 'none'),
      (282, 'Zoe King', 'blazer', 'none'),
      (283, 'David Harris', 'jacket', 'left shoulder'),
      (284, 'Victor White', 'tuxedo', 'none'),
      (285, 'Olivia Brown', 'sweater', 'none'),
      (286, 'Lucas King', 'blouse', 'none'),
      (287, 'Mason White', 'cardigan', 'none'),
      (288, 'Sophia Taylor', 't-shirt', 'none'),
      (289, 'Isabella Harris', 'jacket', 'none'),
      (290, 'Ethan Green', 'blazer', 'none'),
      (291, 'David Brown', 'suit', 'none'),
      (292, 'Olivia King', 'hoodie', 'none'),
      (293, 'Mason Green', 'dress', 'none'),
      (294, 'Victor Brown', 'blouse', 'none'),
      (295, 'Sophia White', 'blazer', 'none'),
      (296, 'Isabella King', 'jacket', 'left hand'),
      (297, 'Zoe Brown', 'cardigan', 'none'),
      (298, 'Mason Taylor', 'sweater', 'none'),
      (299, 'David Harris', 'blouse', 'none'),
      (300, 'Olivia Green', 'suit', 'none'),
      (301, 'Zoe White', 'jacket', 'none'),
      (302, 'Victor Brown', 'sweater', 'none'),
      (303, 'Mason Harris', 'hoodie', 'none'),
      (304, 'Lucas White', 'blazer', 'none'),
      (305, 'Benjamin King', 't-shirt', 'none'),
      (306, 'Isabella Green', 'suit', 'none'),
      (307, 'David Brown', 'blouse', 'none'),
      (308, 'Olivia Walker', 'hoodie', 'none'),
      (309, 'Sophia White', 'blazer', 'none'),
      (310, 'Zoe Taylor', 'dress', 'none'),
      (311, 'Mason Brown', 'sweater', 'none'),
      (312, 'Victor Harris', 'jacket', 'none'),
      (313, 'Sophia Green', 't-shirt', 'none'),
      (314, 'Benjamin Taylor', 'blazer', 'none'),
      (315, 'Zoe Walker', 'hoodie', 'none'),
      (316, 'David King', 'suit', 'none'),
      (317, 'Isabella White', 'blouse', 'none'),
      (318, 'Mason Taylor', 'jacket', 'none'),
      (319, 'Victor Green', 'blazer', 'none'),
      (320, 'Sophia King', 'cardigan', 'none'),
      (321, 'Lucas White', 'sweater', 'none'),
      (322, 'Benjamin Green', 'blouse', 'none'),
      (323, 'Olivia Brown', 'jacket', 'none'),
      (324, 'Victor King', 'hoodie', 'none'),
      (325, 'Zoe Brown', 'suit', 'none'),
      (326, 'Mason Harris', 'blazer', 'none'),
      (327, 'David White', 'cardigan', 'none'),
      (328, 'Olivia King', 'sweater', 'none'),
      (329, 'Sophie Taylor', 'jacket', 'none'),
      (330, 'Isabella Brown', 'blouse', 'none'),
      (331, 'Mason Green', 't-shirt', 'none'),
      (332, 'Lucas White', 'dress', 'none'),
      (333, 'David Harris', 'cardigan', 'none'),
      (334, 'Victor Green', 'jacket', 'none'),
      (335, 'Sophie White', 'blazer', 'none'),
      (336, 'Benjamin Brown', 'suit', 'none'),
      (337, 'Olivia Taylor', 'jacket', 'none'),
      (338, 'Mason Walker', 'blouse', 'none'),
      (339, 'Victor Harris', 'sweater', 'none'),
      (340, 'Zoe Green', 't-shirt', 'none'),
      (341, 'Sophie Taylor', 'hoodie', 'none'),
      (342, 'David White', 'blazer', 'none'),
      (343, 'Lucas Harris', 'suit', 'none'),
      (344, 'Olivia Brown', 'jacket', 'none'),
      (345, 'Victor Green', 't-shirt', 'none'),
      (346, 'Isabella Walker', 'blouse', 'none'),
      (347, 'Benjamin White', 'suit', 'none'),
      (348, 'Mason King', 'cardigan', 'none'),
      (349, 'Sophie Brown', 'dress', 'none'),
      (350, 'David King', 't-shirt', 'none'),
      (351, 'Lucas White', 'blazer', 'none'),
      (352, 'Isabella Green', 'suit', 'none'),
      (353, 'Zoe Brown', 'jacket', 'none'),
      (354, 'Sophie White', 'sweater', 'none'),
      (355, 'Victor Taylor', 'cardigan', 'none'),
      (356, 'Benjamin Walker', 'blouse', 'none'),
      (357, 'Olivia Green', 'suit', 'none'),
      (358, 'Mason White', 'hoodie', 'none'),
      (359, 'David Harris', 'jacket', 'none'),
      (360, 'Victor Brown', 'sweater', 'none'),
      (361, 'Zoe King', 't-shirt', 'none'),
      (362, 'Sophia White', 'blouse', 'none'),
      (363, 'Olivia Brown', 'cardigan', 'none'),
      (364, 'Isabella Green', 'jacket', 'none'),
      (365, 'David Brown', 'blazer', 'none'),
      (366, 'Mason White', 'suit', 'none'),
      (367, 'Victor Green', 'cardigan', 'none'),
      (368, 'Sophie Harris', 'blouse', 'none'),
      (369, 'Benjamin Walker', 'dress', 'none'),
      (370, 'Olivia Brown', 'sweater', 'none'),
      (371, 'Victor Green', 't-shirt', 'none'),
      (372, 'Sophia White', 'blouse', 'none'),
      (373, 'Isabella Taylor', 'cardigan', 'none'),
      (374, 'Mason White', 'dress', 'none'),
      (375, 'David Brown', 'suit', 'none'),
      (376, 'Sophie Green', 'blazer', 'none'),
      (377, 'Lucas White', 't-shirt', 'none'),
      (378, 'Olivia Harris', 'hoodie', 'none'),
      (379, 'Victor White', 'sweater', 'none'),
      (380, 'Sophie Walker', 'jacket', 'none'),
      (381, 'Benjamin Brown', 'blouse', 'none'),
      (382, 'David White', 'cardigan', 'none'),
      (383, 'Lucas Green', 'tuxedo', 'none'),
      (384, 'Sophie Brown', 'dress', 'none'),
      (385, 'Olivia King', 'blazer', 'none'),
      (386, 'Victor Green', 'jacket', 'none'),
      (387, 'Zoe Taylor', 'hoodie', 'none'),
      (388, 'Isabella Walker', 't-shirt', 'none'),
      (389, 'Benjamin Brown', 'blazer', 'none'),
      (390, 'Mason Green', 'suit', 'none'),
      (391, 'David Walker', 'cardigan', 'none'),
      (392, 'Olivia Brown', 'jacket', 'none'),
      (393, 'Victor White', 'tuxedo', 'none'),
      (394, 'Sophia Green', 'dress', 'none'),
      (395, 'Isabella Brown', 'suit', 'none'),
      (396, 'David King', 'blazer', 'none'),
      (397, 'Mason White', 'hoodie', 'none'),
      (398, 'Victor Taylor', 'cardigan', 'none'),
      (399, 'Olivia Harris', 'sweater', 'none'),
      (400, 'Benjamin Walker', 'jacket', 'none')
    ;`,

  // Create and populate the interviews table
  `CREATE TABLE interviews (
      suspect_id INTEGER,
      transcript TEXT,
      FOREIGN KEY(suspect_id) REFERENCES suspects(id)
    );`,
  `INSERT INTO interviews (suspect_id, transcript) VALUES
      (1, NULL),
      (2, 'I was at home the whole day, no idea what happened.'),
      (3, NULL),
      (4, 'I have no recollection of that event.'),
      (5, 'I was at work, couldn’t have been involved.'),
      (6, NULL),
      (7, 'I was with friends at a restaurant.'),
      (8, 'I don’t know anything about the incident.'),
      (9, NULL),
      (10, 'I didn’t even know anything was going on.'),
      (11, NULL),
      (12, 'I didn’t see anything suspicious at all.'),
      (13, NULL),
      (14, 'I was traveling out of town.'),
      (15, NULL),
      (16, 'I was with family the entire evening.'),
      (17, 'I was sleeping at that time.'),
      (18, NULL),
      (19, 'I have no idea about the situation.'),
      (20, NULL),
      (21, 'I heard nothing, I was watching a movie.'),
      (22, 'I was stuck in traffic, didn’t see anything.'),
      (23, NULL),
      (24, 'I have no clue about that event.'),
      (25, NULL),
      (26, 'I wasn’t even in the area, sorry.'),
      (27, 'I have no connection with the incident.'),
      (28, NULL),
      (29, 'I wasn’t near the place at all.'),
      (30, NULL),
      (31, 'I wasn’t part of any of that.'),
      (32, NULL),
      (33, 'I had no part in anything going on.'),
      (34, NULL),
      (35, 'I wasn’t involved in anything suspicious.'),
      (36, 'I was out with friends, didn’t even hear about it.'),
      (37, NULL),
      (38, 'I’m not sure what happened, but I wasn’t near.'),
      (39, NULL),
      (40, 'I have no idea about the situation.'),
      (41, NULL),
      (42, 'I wasn’t anywhere near that area.'),
      (43, 'I don’t know anything about it, sorry.'),
      (44, NULL),
      (45, 'I was busy at work, no time for anything else.'),
      (46, NULL),
      (47, 'I had nothing to do with it, I’m innocent.'),
      (48, NULL),
      (49, 'I didn’t even know it was happening.'),
      (50, 'I was with a friend the whole time.'),
      (51, NULL),
      (52, 'I wasn’t there, and I don’t know anything.'),
      (53, NULL),
      (54, 'I’m not involved in any way.'),
      (55, NULL),
      (56, 'I didn’t hear anything, I was busy.'),
      (57, NULL),
      (58, 'I didn’t see anything strange.'),
      (59, NULL),
      (60, 'I don’t know anything about what happened.'),
      (61, NULL),
      (62, 'I was out of town that day, no idea.'),
      (63, NULL),
      (64, 'I didn’t see anything unusual happening.'),
      (65, NULL),
      (66, 'I wasn’t involved, I have an alibi.'),
      (67, 'I wasn’t part of it, I swear.'),
      (68, NULL),
      (69, 'I didn’t even know there was something going on.'),
      (70, 'I have nothing to do with this.'),
      (71, NULL),
      (72, 'I was at the store, nothing to do with it.'),
      (73, 'I wasn’t in the area, I have proof.'),
      (74, NULL),
      (75, 'I don’t know anything, I swear.'),
      (76, NULL),
      (77, 'I was nowhere near there.'),
      (78, 'I was at home, minding my business.'),
      (79, NULL),
      (80, 'I wasn’t part of any of this.'),
      (81, 'I didn’t hear anything that night.'),
      (82, NULL),
      (83, 'I don’t know, I wasn’t there.'),
      (84, NULL),
      (85, 'I had no idea what was happening.'),
      (86, NULL),
      (87, 'I didn’t see anything strange at all.'),
      (88, NULL),
      (89, 'I don’t know anything about it.'),
      (90, 'I was with my friends, no involvement.'),
      (91, NULL),
      (92, 'I was at home, nothing happened around me.'),
      (93, NULL),
      (94, 'I don’t even know what happened.'),
      (95, 'I was elsewhere, couldn’t be me.'),
      (96, NULL),
      (97, 'I wasn’t near there, I promise.'),
      (98, NULL),
      (99, 'I don’t even know about the crime.'),
      (100, 'I wasn’t near the place, no idea.'),
      (101, NULL),
      (102, 'I wasn’t there, I can prove it.'),
      (103, 'I have nothing to say about it.'),
      (104, NULL),
      (105, 'I didn’t hear anything or see anything.'),
      (106, NULL),
      (107, 'I’m innocent, I didn’t do anything.'),
      (108, NULL),
      (109, 'I wasn’t in town during the incident.'),
      (110, NULL),
      (111, 'I don’t know who’s behind this.'),
      (112, 'I wasn’t anywhere near there, I swear.'),
      (113, NULL),
      (114, 'I didn’t even know about the crime.'),
      (115, NULL),
      (116, 'I was busy with work, didn’t notice anything.'),
      (117, 'I didn’t see anything, I was out of town.'),
      (118, NULL),
      (119, 'I’m not involved at all, I promise.'),
      (120, 'I don’t know anything about the theft.'),
      (121, NULL),
      (122, 'I wasn’t there at all, couldn’t have done anything.'),
      (123, 'I had no part in this, I swear.'),
      (124, NULL),
      (125, 'I don’t even know who you are talking about.'),
      (126, 'I wasn’t involved, I didn’t even hear about it.'),
      (127, NULL),
      (128, 'I wasn’t near that place, no connection at all.'),
      (129, 'I wasn’t involved, trust me.'),
      (130, NULL),
      (131, 'I was with a friend all night.'),
      (132, NULL),
      (133, 'I wasn’t in town that evening, no way.'),
      (134, NULL),
      (135, 'I didn’t even know about the incident.'),
      (136, NULL),
      (137, 'I wasn’t near the area at all.'),
      (138, 'I was at the gym, can’t be me.'),
      (139, NULL),
      (140, 'I didn’t see anything that night.'),
      (141, 'I don’t know anything, sorry.'),
      (142, NULL),
      (143, 'I didn’t hear or see anything, I was in bed.'),
      (144, 'I wasn’t there, I’m innocent.'),
      (145, NULL),
      (146, 'I wasn’t even close to the crime scene.'),
      (147, NULL),
      (148, 'I was with family, didn’t see anything.'),
      (149, NULL),
      (150, 'I wasn’t involved, I swear on my life.'),
      (151, NULL),
      (152, 'I don’t know anything, I wasn’t there.'),
      (153, 'I have no connection to the incident.'),
      (154, NULL),
      (155, 'I wasn’t part of this, I have an alibi.'),
      (156, 'I don’t know anything about the crime.'),
      (157, NULL),
      (158, 'I didn’t see anything, I was busy at work.'),
      (159, 'I don’t know anything about the theft.'),
      (160, NULL),
      (161, 'I wasn’t near the crime scene, I swear.'),
      (162, NULL),
      (163, 'I don’t even know about it, sorry.'),
      (164, NULL),
      (165, 'I wasn’t there, I promise.'),
      (166, NULL),
      (167, 'I wasn’t involved in any way, I swear.'),
      (168, 'I didn’t see anything suspicious.'),
      (169, NULL),
      (170, 'I don’t know what you are talking about.'),
      (171, NULL),
      (172, 'I didn’t even hear about the crime.'),
      (173, 'I wasn’t near the scene.'),
      (174, NULL),
      (175, 'I have no involvement in this.'),
      (176, 'I didn’t hear anything, I was asleep.'),
      (177, NULL),
      (178, 'I wasn’t involved at all, I swear.'),
      (179, 'I was working that day, can’t be me.'),
      (180, NULL),
      (181, 'I wasn’t near the place, I didn’t see anything.'),
      (182, NULL),
      (183, 'I wasn’t going to steal it, but I did.'),
      (184, 'I have no clue what happened.'),
      (185, NULL),
      (186, 'I was at home that day, I didn’t know.'),
      (187, 'I wasn’t part of it, I swear.'),
      (188, NULL),
      (189, 'I don’t know anything about it, I wasn’t there.'),
      (190, 'I wasn’t involved in any of this.'),
      (191, NULL),
      (192, 'I didn’t see anything, I swear.'),
      (193, 'I wasn’t around there, I was busy at work.'),
      (194, NULL),
      (195, 'I didn’t even know about the crime.'),
      (196, NULL),
      (197, 'I have no idea who did this.'),
      (198, NULL),
      (199, 'I wasn’t involved, I was at the park.'),
      (200, 'I didn’t see anything suspicious, sorry.')
    ;`,
];
